name: CI/CD workflow for Maven Build and Sonar Code Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Maven
      run: mvn -version

    - name: Build with Maven
      run: mvn clean install -f MyWebApp/pom.xml

  sonar_scan:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=hell-yeah-maker
          -Dsonar.projectKey=newdude
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Fail the job if Quality Gate fails
    - name: Fail if Quality Gate fails
      run: |
        if [[ "${{ steps.sonarqube-quality-gate.outputs.quality-gate-status }}" != "PASSED" ]]; then
          echo "❌ SonarQube Quality Gate failed!"
          exit 1
        fi
      shell: bash
